version: '3.8'
services:
  kong:
    image: kong:2.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
  
  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    volumes:
      - ./api-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3003:3003"


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: workout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hamburger3202
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  

volumes:
  db: